Removed variable import, passed it with function
ERROR REPAIRING: ImportError: cannot import name 'csvFile'
from partially initialized module 'app'
(most likely due to a circular import)